### ISSUE TITLE
Add Bows to Prison Vote Crates & Update Prison Kits

### ISSUE THREAD

**Issue by SwiftSwamp** [SwiftSwamp/GlacialRealms#1]
* Add Bows to the Prison Vote Crates
* Update the Prison Kits with the new revamped kits (Reference Doc: GlacialRealms - Prison)

**Comment by CosmicFyre** [comment]
Bows are already included in kits, what Hunting meant in his suggestion was adding bows to vote crates.

**Comment by SwiftSwamp** [comment]
Ahh, thanks. Updated.

**Comment by SwiftSwamp** [comment]
* This has been since implemented
