### ISSUE TITLE
Add Pets

### ISSUE THREAD

**Issue by SwiftSwamp** [SwiftSwamp/GlacialRealms#21]
* Add Pets to Creative, Prison & Skyblock
* Add Pet Packs to the Store (Making some exclusive to the pack)
* Add Pets to each rank

**Comment by CosmicFyre** [comment]
penguin?

**Comment by GetDerpy** [comment]
^ one of the pets should be a baby SwiftSwamp

**Comment by SwiftSwamp** [comment]
They added Polar Bears but not Penguins to 1.10 ):
