### ISSUE TITLE
Don't allow crafting of Gapples, Beacons or Hoppers in Factions

### ISSUE THREAD

**Issue by SwiftSwamp** [SwiftSwamp/GlacialRealms#23]
* Disable crafting of Gapples, Beacons & Hoppers

**Comment by GetDerpy** [comment]
Allow crafting of gapples or zp spawners are useless.

**Comment by SwiftSwamp** [comment]
You guys should all have access to the reset doc and no one said anything when it was brought up in the group chat, speak with LeBlanc but I get your point.

**Comment by SwiftSwamp** [comment]
* Gapples have been disabled based on LeBlanc's and I's discussion, please take it up with LeBlanc in PM if you still disagree.
