### ISSUE TITLE
Price Changes on Skyblock

### ISSUE THREAD

**Issue by SwiftSwamp** [SwiftSwamp/GlacialRealms#25]
* Add in the Squid Spawner
* Change Mob Spawner prices (Doc Reference: GlacialRealms - Skyblock)
* Adjust Mob Drop prices (Doc Reference: GlacialRealms - Skyblock)

**Comment by CosmicFyre** [comment]
guardian spawners?

**Comment by SwiftSwamp** [comment]
* Implemented
