### ISSUE TITLE
Rename item bug

### ISSUE THREAD

**Issue by xadistic** [SwiftSwamp/GlacialRealms#67]
After you rename a pick on Prison, you are unable to use autosell until you buy another enchant with tokens.

**Comment by SwiftSwamp** [comment]
that's extremely odd... investigating.

**Comment by SwiftSwamp** [comment]
I just tried it, I was still able to autosell.
What are you renaming the pickaxe to?

**Comment by xadistic** [comment]
"&d&lRoad to 20mil Blocks Mined"

**Comment by SwiftSwamp** [comment]
Please open a new issue here if it's still happening: http://GlacialRealms.com/issues , I'm unable to recreate.
