### ISSUE TITLE
Tropical Skyblock Island Bug

### ISSUE THREAD

**Issue by xadistic** [SwiftSwamp/GlacialRealms#68]
Choosing tropical island as a new player automatically gives you 710 levels.

Example is IGN: CusTrain

**Comment by SwiftSwamp** [comment]
All of the islands automatically give you ~700 levels, is there a specific item on these islands that are overly expensive?

**Comment by xadistic** [comment]
Not sure. The first island doesn't which is why I added it. Not sure what island it is as I have the regular island

**Comment by SwiftSwamp** [comment]
Ahh yeah, all of the other islands are pre-built, however 400-700 levels is quite a bit.. let me paste them in and see what blocks might be overly expensive.

**Comment by SwiftSwamp** [comment]
Ahh, it was the unobtainable block we were using as part of the clouds (Cobwebs), I've set them to 0 and the island levels by default are much lower now, thanks!
