### ISSUE TITLE
/sell all spamming chat + shop additions

### ISSUE THREAD

**Issue by GetDerpy** [SwiftSwamp/GlacialRealms#70]
Currently when you /sell all, it sells each stack of items individually and spams your chat.

What should happen is, it sells your entire inventory and says "Sold xxx items for $xxx".

Also please add the following to the shop:

Raiding supplies:
- Ladder [B: 10 - S: 0]
- Trap Door [B: 10 - S: 0]
- Creeper Egg [B: 45000 - S: 0]
- Furnace [B: 15 - S: 0]

Brewing:
- Netherwart [B: 15 - S: 5]
- Pufferfish [B: 120 - S: 12]

**Comment by SwiftSwamp** [comment]
* Sell All Spam has been corrected along with a much nicer message output
* Items have been added / adjusted.
