### ISSUE TITLE
Enchanting Table Issues

### ISSUE THREAD

**Issue by GetDerpy** [SwiftSwamp/GlacialRealms#72]
- When you put an item in the table that is "unenchantable" and hotkey it out, your item is lost and you are left with a glitched book
- Fishing rods are considered "unenchantable" so you can not get fishing rod based enchants
- When you put an item in the table to enchant, it always says "smite" is what you will get even if you don't get smite.

**Comment by SwiftSwamp** [comment]
For the last one, what item are you using and what levels? I've tested it with Axes and Swords and it's not saying I'm going to get Smite at all.

**Comment by GetDerpy** [comment]
https://gyazo.com/d8b9b0211fab19beed8517cf2a7d1486
https://gyazo.com/969dee52288f8405a6dfb5ec771461c4

To be honest, now that we don't enchant ce's with enchant tables, and the max tier of every enchant is available in /xpshop, why don't we just disable enchant tables?

**Comment by SwiftSwamp** [comment]
That's just a cosmetic bug, not really a big deal?
And don't believe like Enchantment Tables :P
