### ISSUE TITLE
XPShop Enchants

### ISSUE THREAD

**Issue by GetDerpy** [SwiftSwamp/GlacialRealms#73]
Add the following to the /xpshop enchants:

- Efficiency 5
- Aqua Affinity 1
- Blast Protection 4
- Flame 1
- Power 4
- Infinity 1
- Fortune 3
- Luck Of The Sea 3
- Lure 3
- Projectile Protection 4
- Respiration 3
- Silk Touch 1
- Thorns 3

**Comment by GetDerpy** [comment]
Commenting to test alert

**Comment by SwiftSwamp** [comment]
Could we update this with prices please and any changes to the current ones.

**Comment by GetDerpy** [comment]
4k for all

**Comment by GetDerpy** [comment]
This was closed but not done?
