### ISSUE TITLE
Skyblock Hoppers Not Transferring Items

### ISSUE THREAD

**Issue by xadistic** [SwiftSwamp/GlacialRealms#75]
Hoppers on Skyblock are not transferring items or transferring them extremely slowly.

**Comment by SwiftSwamp** [comment]
We'll be adding some cool Multiblock structures that allow you to Overclock Hoppers, make massive pipe lines and do some cool auto sorting features, currently what happens is that so many Hoppers get built up that the server can't process it all so it get's sent in a "Queue", once the queue is finished and the server catches up then your items are transferred.
